export const modalsData = {
  tgZMeter: { ref: 'tgZMeter', title: '台区电表明细', componentName: 'tg-elec-meter-detail' },
  tgCons: { ref: 'tgCons', title: '低压居民明细', componentName: 'low-power-person-detail' },
  tgGcCons: { ref: 'tgGcCons', title: '分布式电源', componentName: 'distributed-power' },
  tgTmnl: { ref: 'tgTmnl', title: '终端地址', componentName: 'terminal-id' },
  tgLineLoseCalcModel: { ref: 'tgLineLoseCalcModel', title: '台区线损计算模型', componentName: 'tg-line-loss-count-model' },
  tgLineLosePower: { ref: 'tgLineLosePower', title: '线损数据监测', componentName: 'line-loss-power' },
  tgLoadDetail: { ref: 'tgLoadDetail', title: '负载率统计', componentName: 'load-rate-statistics' },
  tgReadDetail: { ref: 'tgReadDetail', title: '采集明细', componentName: 'collection-details' },
  tgCoverDetail: { ref: 'tgCoverDetail', title: '采集覆盖明细', componentName: 'collection-cover-detail' },
  tgPowerCalcErrorDetail: { ref: 'tgPowerCalcErrorDetail', title: '电量计算失败明细', componentName: 'power-count-alarm' },
  tgUncoverDetail: { ref: 'tgUncoverDetail', title: '未覆盖电表明细', componentName: 'no-cover-elec-meter' },
  tgPowerAbnormalDetail: { ref: 'tgPowerAbnormalDetail', title: '用电异常', componentName: 'use-elec-alarm' },
  tgDataAbnormalDetail: { ref: 'tgDataAbnormalDetail', title: '档案异常明细', componentName: 'file-alarm-detail' },
  tgDistributionAbnormalDetail: { ref: 'tgDistributionAbnormalDetail', title: '配变异常', componentName: 'distribution-transformer-alarm' },
  tgZeroPowerDetail: { ref: 'tgZeroPowerDetail', title: '零电量电表明细', componentName: 'zero-volume-meter-detail' },
  tgMeteringAbnormalDetail: { ref: 'tgMeteringAbnormalDetail', title: '计量异常', componentName: 'metering-alarm' },
  tgStealElectricityDetail: { ref: 'tgStealElectricityDetail', title: '疑似窃电户明细', componentName: 'stealing-elec-detail' },
  tgChangeMetDetail: { ref: 'tgChangeMetDetail', title: '换表记录', componentName: 'change-met' },
  I96datas: { ref: 'datas96', title: '96点信息', componentName: 'datas96' },
  U96datas: { ref: 'datas96', title: '96点信息', componentName: 'datas96' },
  P96datas: { ref: 'datas96', title: '96点信息', componentName: 'datas96' },
  tgChangeFactorDetail: { ref: 'tgChangeFactorDetail', title: '换倍率记录', componentName: 'change-factor' }
}
